sudo: required
services:
  - docker

before_install:
  - docker build -t swapnilkhante/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run swapnilkhante/react-test npm test -- --coverage

after_success:
  - docker build -t swapnilkhante/multi-client -f ./client
  - docker build -t swapnilkhante/multi-nginx -f ./nginx
  - docker build -t swapnilkhante/multi-server -f ./server
  - docker build -t swapnilkhante/multi-worker -f ./worker

# log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

# Push to docker images to docker hub
  - docker push swapnilkhante/multi-client
  - docker push swapnilkhante/multi-nginx
  - docker push swapnilkhante/multi-server
  - docker push swapnilkhante/multi-worker

  